<template>
  <v-row justify="center">
    <v-dialog v-model="visible" fullscreen hide-overlay transition="dialog-bottom-transition">
      <v-card>
      <wizard
        title="Create dashboard"
        :steps="steps"
        :step="currentStep"
        :alert.sync="alert"
        :wait="waiting"
        @next="onNext"
        @prev="onPrev"
        @done="onDone"
        @cancel="onCancel">

        <template #Welcome>
          <p>
            Before we can create your personal dashboard, we need to collect some information.
          </p>
          <p>
            In the next couple of steps we will ask you to run a script that collects some information about your shell
            including your shell variables, aliases, and history.
            The report generated by the script is a plain text file that you can edit with your favourite editor to
            remove any sensitive or personally identifying information.
            You will then upload the report locally in your browser so you can review it one more time before submitting
            it for analysis.
          </p>
          <p>
            Once you've submitted the report, we'll get your personal dashboard configured for you.
          </p>
        </template>

        <template #Upload>
          <report-wizard-upload
            :error-message.sync="fileError"
            @change="loadReport">
          </report-wizard-upload>
        </template>

        <template #Review>
          <report-wizard-review
            :report="fileContent"
          >
          </report-wizard-review>
        </template>


        <template #Summary>
          <ReportUploadWizardSummary
            :contact.sync="contact"
            :email.sync="email"
            :is-valid-email.sync="isValidEmail"
            :submission-id="submissionId"
          ></ReportUploadWizardSummary>
        </template>
      </wizard>
      </v-card>
    </v-dialog>

<!--    Consent dialog-->
    <v-dialog
      v-model="requestConsent"
      max-width="300"
    >
      <notification
        title="Submit report?"
        text="Your data will be used to understand how developers use their shells. Your data will only be examined by the research team."
      >
        <template>
          <v-btn
            color="green darken-1"
            text
            @click="requestConsent = false"
          >
            Disagree
          </v-btn>
          <v-btn
            color="green darken-1"
            text
            @click="submitReport"
          >
            Agree
          </v-btn>
        </template>
      </notification>
    </v-dialog>

    <!-- Email error dialog -->
    <v-dialog
      v-model="emailError"
      max-width="300"
    >
      <notification
        title="Something went wrong."
        :text="'There was a problem sending the e-mail. Your submission id is ' + submissionId + '. We\'ll still show you your dashboard.'"
      >
        <template>
          <v-btn
            color="green darken-1"
            text
            @click="finish"
          >
            Okay
          </v-btn>
        </template>
      </notification>

    </v-dialog>
  </v-row>
</template>

<script lang="ts">
  import Vue from 'vue'
  import Component from 'vue-class-component'
  import NotificationArea from "@/components/NotificationArea.vue";
  import Wizard from "@/components/Wizard.vue";
  import ReportUploadWizardSummary from "@/components/ReportWizardSummary.vue";
  import ReportWizardUpload from "@/components/ReportWizardUpload.vue";
  import ReportWizardReview from "@/components/ReportWizardReview.vue";
  import Notification from "@/components/Notification.vue";

  @Component({
    components: {
      Notification,
      ReportWizardReview,
      ReportWizardUpload,
      ReportUploadWizardSummary,
      NotificationArea,
      Wizard
    }
  })
  export default class DataCollection extends Vue {
    // Wizard state
    steps = ["Welcome", "Upload", "Review", "Summary"];
    currentStep = 1;
    visible = true;
    alert = {
      title: "",
      text: "",
      visible: false
    }
    waiting = false;

    // Upload step state
    file?: File;
    fileLoaded = false;
    fileError = "";
    fileContent = "";

    // Review step state
    requestConsent = false;

    // Summary step state
    submissionId = "";
    email = "";
    contact = true;
    isValidEmail = true;
    emailError = false;

    onNext() {
      if (this.currentStep === 2 && !this.fileLoaded) {
        this.alert = {
          title: "No file selected.",
          text: "Please upload the report generated by the script.",
          visible: true,
        }
        return;
      }

      if (this.currentStep === 3) {
        this.requestConsent = true;
        return;
      }

      this.currentStep++;
    }

    onPrev() {
      this.currentStep--;
    }

    async onDone() {
      if (!this.isValidEmail) {
        this.alert = {
          title: "Invalid email.",
          text: "Please provide a valid email address or leave the field blank.",
          visible: true,
        }
        return;
      }

      if (this.email.length > 0) {
        this.waiting = true
        try {
          // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
          // @ts-ignore
          await this.$emailService.post({email: this.email, contact: this.contact, submissionId: this.submissionId})
        } catch (err) {
          console.error(err);
          this.emailError = true;
        } finally {
          this.waiting = false;
        }

      }

      if (!this.emailError) {
        this.finish();
      }
    }

    onCancel() {
      this.$emit("close")
    }

    async loadReport(file: File) {
      this.waiting = true
      this.file = file

      try {
        this.fileContent = await file.text()
        this.fileLoaded = true;
      } catch (err) {
        console.log(`ReportWizard::loadReport(..) - ${err}`);
        this.fileError = `There was an error loading the selected file.`;
      } finally {
        this.waiting = false
      }
    }

    finish() {
      this.$emit("finish");
    }

    async submitReport() {
      this.requestConsent = false;
      this.waiting = true

      try {
        // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
        // @ts-ignore
        await this.$reportService.post(this.file)
        // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
        // @ts-ignore
        this.submissionId = this.$reportService.reportId;
        this.currentStep++;
      } catch (err) {
        console.error(`ReportWizard::submitReport() - ${err}`);
        this.alert = {
          title: "Failed to submit.",
          text: "There was an error submitting the report.",
          visible: true,
        }
      } finally {
        this.waiting = false
      }
    }
  }
</script>

<style scoped>

</style>
